services:
  - type: web
    name: calendar-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn calendar_app.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: calendar_app.settings
      - key: SECRET_KEY
        value: 'django-insecure-#nx#yv#bh4f@0oqh#k7^i&q@-ry_v0ked4elhl!ohit^d!6vj&'
      - key: DEBUG
        value: "False"
      - key: GOOGLE_CLIENT_ID
        value: your-client-id-here
      - key: GOOGLE_CLIENT_SECRET
        value: your-client-secret-here
      - key: REDIRECT_URI
        value: https://calendar-app.onrender.com/oauth2callback
    postDeployCommand: |
      echo "Running migrations..."
      python manage.py migrate || { echo "Migration failed"; exit 1; }
      echo "Migrations completed."