services:
  - type: web
    name: calendar-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn calendar_app.wsgi:application --log-file -
    postDeployCommand: |
      echo "Running migrations..."
      python manage.py migrate || { echo "Migration failed"; exit 1; }
      echo "Migrations completed."